### ISSUE TITLE
Cancel from android time picker does not trigger picker open next time

### ISSUE THREAD

**Issue by gomathisolai16** [Navybits/react-native-navybits-date-time-picker#10]
Am using this.refs.dateSelector.refs.Picker.onPressDate() this to open picker by custom click event.
While click cancel it closed the picker , but  i have to click double time to open picker next time. It happens only in android, for ios its working fine. Any one has solution for this issue?

**Comment by maheshj1105** [comment]
I am having the same issue, is there any update on this?

**Comment by HananeAlSamrout** [comment]
this is fixed, i will upload changes soon , thanks for reporting
