### ISSUE TITLE
Open picker on custom button click or some other event, instead of default text click.

### ISSUE THREAD

**Issue by NarendraSingh88** [Navybits/react-native-navybits-date-time-picker#7]
Hello,
I need to open this date/time picker through a function / event, instead of opening it from default text click.
Any way to achieve that?

**Comment by HananeAlSamrout** [comment]
for now try giving it a ref "dateSelector" and open it this way 
`this.refs.dateSelector.refs.Picker.onPressDate() `
this will be fixed later

**Comment by NarendraSingh88** [comment]
It worked for now (Y).
